# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    data_directory: '/mnt/bfs/'
    coverImg_directory: 'img/'
    time_zone: 'Asia/Shanghai'
    SMSAccessKeyId :
    SMSAccessKeySecret :
    bfs_flag : '/home/bfs/sandbox/bfs.flag'
    apady_directory : '/var/www/html/apady/public/'
