# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    data_directory: '/mnt/bfs/'
    coverImg_directory: 'img/'
    SMSAccessKeyId : 'LTAIs0Rznap5KAZN'
    SMSAccessKeySecret : 'glPRtsyHTFqRbtVmFob1wzw9t0XZuT'
    bfs_flag : '/home/bfs/sandbox/bfs.flag'
    apady_directory : '/var/www/html/apady/public/'
    time_zone: 'Asia/Shanghai'

services:
    # default configuration for services in *this* file
    _defaults:
        bind:
          $SMSAccessKeyId: '%SMSAccessKeyId%'
          $SMSAccessKeySecret: '%SMSAccessKeySecret%'
          $redisDSN: 'redis://localhost'

        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
